### ISSUE TITLE
readProcessWithExitCode "ghc-pkg" ["dump"] "" fail (Permission denied)

### ISSUE THREAD

**Issue by dontdieych** [haskell/process#72] opened 2016-10-02 11:23 UTC
Windows 7 64bit Korean version (CP949)
MSYS2 Shell (LANG=C.UTF-8)

```
$ stack --version
Version 1.2.1, Git revision 7a54085361260a469815b9aa408264bee4cd68e4 x86_64 hpack-0.14.1
```

`stack exec ghc-pkg dump` working well on shell but,

```
Prelude System.Process> (a, b, c) <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
*** Exception: terminateProcess: permission denied (Permission denied)
Prelude System.Process>
```

`readProcessWithExitCode "ghc-pkg" ["list"] ""` is working good.

I've found this problem when I'm trying `stack hoogle` command.

https://github.com/commercialhaskell/stack/issues/2582

**Comment by snoyberg** [comment] 2016-10-02 11:29
I'm unable to reproduce on OS X. Can you try putting together a script to repro to make sure we're clear on the GHC version and package version being used? E.g.

```haskell
#!/usr/bin/env stack
-- stack --resolver ghc-8.0.1 runghc
import System.Process

main :: IO ()
main = do
    _ <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
    return ()
```

**Comment by dontdieych** [comment] 2016-10-02 12:04
Working good with `-- stack --resolver ghc-8.0.1 runghc` but `-- stack --resolver lts-6.6 runghc`.

```
Administrator@PC042 ~/iiac-patch-label-list-generator> stack lts-6.6.sh
lts-6.6.sh: terminateProcess: permission denied (Permission denied)
Administrator@PC042 ~/iiac-patch-label-list-generator> echo $status
1
Administrator@PC042 ~/iiac-patch-label-list-generator> stack 8.0.1.sh
Administrator@PC042 ~/iiac-patch-label-list-generator> echo $status
0
Administrator@PC042 ~/iiac-patch-label-list-generator> cat lts-6.6.sh
#!/usr/bin/env stack
-- stack --resolver lts-6.6 runghc
import System.Process

main :: IO ()
main = do
    _ <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
    return ()
Administrator@PC042 ~/iiac-patch-label-list-generator> cat 8.0.1.sh
#!/usr/bin/env stack
-- stack --resolver ghc-8.0.1 runghc
import System.Process

main :: IO ()
main = do
    _ <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
    return ()
Administrator@PC042 ~/iiac-patch-label-list-generator>
```

**Comment by snoyberg** [comment] 2016-10-02 12:17
Alright, this is good at narrowing things down. Next I'd like to figure out if this is caused by GHC 7.10.3 vs 8.0.1, or by process 1.2.3.0 vs 1.4.2.0. Can you try running with:

```haskell
-- stack --resolver ghc-7.10.3 runghc --package process-1.4.2.0
```

**Comment by dontdieych** [comment] 2016-10-02 12:31
```
Administrator@PC042 ~/iiac-patch-label-list-generator> stack lts-6.6.sh
lts-6.6.sh: terminateProcess: permission denied (Permission denied)
Administrator@PC042 ~/iiac-patch-label-list-generator> echo $status
1
Administrator@PC042 ~/iiac-patch-label-list-generator> stack 7.10.3_1.4.2.0.sh
Administrator@PC042 ~/iiac-patch-label-list-generator> echo $status
0
Administrator@PC042 ~/iiac-patch-label-list-generator> cat lts-6.6.sh
#!/usr/bin/env stack
-- stack --resolver lts-6.6 runghc
import System.Process

main :: IO ()
main = do
    _ <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
    return ()
Administrator@PC042 ~/iiac-patch-label-list-generator> cat 7.10.3_1.4.2.0.sh
#!/usr/bin/env stack
-- stack --resolver ghc-7.10.3 runghc --package process-1.4.2.0
import System.Process

main :: IO ()
main = do
    _ <- readProcessWithExitCode "ghc-pkg" ["dump"] ""
    return ()
Administrator@PC042 ~/iiac-patch-label-list-generator>
```

**Comment by snoyberg** [comment] 2016-10-02 12:38
If I'm reading this correctly, it looks like the bug has already been
resolved in the newest version of process, do you agree?

**Comment by dontdieych** [comment] 2016-10-02 12:40
Yes, I'm running `stack hoogle` with lts-7.2.

Wish me luck. Thanks.

**Comment by snoyberg** [comment] 2016-10-02 12:44
You'll probably need to recompile stack with LTS 7, unless the bug was
triggered in the Hoogle executable instead.

**Comment by ndmitchell** [comment] 2016-10-02 12:45
I'm pretty sure it was inside Hoogle, not Stack.

**Comment by dontdieych** [comment] 2016-10-03 06:00
I've got another error during `stack hoogle` command.

https://github.com/ndmitchell/hoogle/issues/188

**Comment by ndmitchell** [comment] 2016-11-24 20:05
Sounds like this issue was in process, but got fixed in a higher version, so closing.

**Closed by ndmitchell** 2016-11-24 20:05 UTC
